# bipedal-locomotion-framework requires 10.13 for std::bad_cast_any
# robometry requeries 10.15 for std::filesystem
MACOSX_DEPLOYMENT_TARGET:      # [osx and x86_64]
  - 10.15                      # [osx and x86_64]

qt:
  - 5.15

qt_main:
  - 5.15
  
ipopt:
  - 3.14.8

# Some packages (vtk) to build require a specific version of boost but without
# any run or run_dependency
# Workaround for https://github.com/robotology/robotology-superbuild/pull/1277
boost:
  - 1.78.0
boost_cpp:
  - 1.78.0
